version: '3.8'

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "80:80"
    networks:
      - vinilo-net
    restart: always

networks:
  vinilo-net:
    driver: bridge
